### ISSUE TITLE
Command mapping by user input

### ISSUE THREAD

**Issue by LittleYenMin** [LittleYenMin/jieba-bot#4]
As title, 
for example: 
input: 我想查`曠課` (as we know, it looks like `我想`, `查`, `曠課` after processed)
output mapping: `昌昌;曠課` by `曠課`

**Comment by dannypsnl** [comment]
For now, we could use exact matching for the purpose: if we found `曠課` in the sequence provided by **Jeiba** then we say users want to execute the command: `昌昌;曠課`

**Comment by dannypsnl** [comment]
It would like:
```
for word in word_sequence:
  if word == '曠課':
    return ok('昌昌;曠課')
  return err('not found')
```

**Comment by LittleYenMin** [comment]
#6 according to this PR, maybe we need to consider multiple intents when user type?
for example: `我想要查成績跟曠課` > [`昌昌;成績`, `昌昌曠課`]

**Comment by dannypsnl** [comment]
According to what you want to do, I suggest while appear 成績 跟 曠課 sequence(without any medium word), then we say they both are targets.

And now we should consider users do want to search their score? What if they say 我的成績很慘, but the bot show their score that sounds poor.

**Comment by LittleYenMin** [comment]
Well... Is it time to do the NLU stuff?

**Comment by dannypsnl** [comment]
For me? Yes.

**Comment by LittleYenMin** [comment]
It's a huge challenge. I found a lib probably what we want.
[Rasa NLU](https://github.com/RasaHQ/rasa_nlu)

**Comment by LittleYenMin** [comment]
[Rasa NLU for Chinese support](https://github.com/crownpku/rasa_nlu_chi)

**Comment by dannypsnl** [comment]
Basically what we want to do is **Text Understanding**

**Comment by LittleYenMin** [comment]
What do you mean?
Training our own model by Rasa NLU is not what we want?

**Comment by dannypsnl** [comment]
> I don’t get it.
> Training our own model by Rasa NLU is not what we want?

Yes, Rasa seems like what we need here, that's a comment for noting the keyword.

**Comment by LittleYenMin** [comment]
Simple data struct for our NLU model (prototype)
```
{
 "entities": [{text: "成績"}, {"text": "曠課"}]
 "intent": "search"
}
```

what do you think?

**Comment by LittleYenMin** [comment]
here it's the step I plan to do with TF-IDF and cosine similarity
1. analysis of the TF-IDF value of the text sequence by jieba.
2. cosine similarity all listed questions.
3. return and rank the top N result

what do you think?

**Comment by dannypsnl** [comment]
Your first link seems missing; it goes to jeiba official page

**Comment by LittleYenMin** [comment]
fixed XDD

**Comment by dannypsnl** [comment]
Seems like iPhone problem, my computer goes to the correct URL but phone not

**Comment by dannypsnl** [comment]
> here it's the step I plan to do with TF-IDF and cosine similarity
> 
> 1. analysis of the TF-IDF value of the text sequence by jieba.
> 2. cosine similarity all listed questions.
> 3. return and rank the top N result
> 
> what do you think?
> 
> References
> [基于 TF-IDF 算法的关键词抽取(jieba)](https://github.com/fxsjy/jieba#%E5%9F%BA%E4%BA%8E-tf-idf-%E7%AE%97%E6%B3%95%E7%9A%84%E5%85%B3%E9%94%AE%E8%AF%8D%E6%8A%BD%E5%8F%96)
> [TF-IDF与余弦相似性的应用](http://www.ruanyifeng.com/blog/2013/03/cosine_similarity.html)

Please more carefully pick the reference, Jieba is based on TF_IDF to get keywords, not give you the TF_IDF matrix.

**Comment by dannypsnl** [comment]
We want to calculate the **Cosine similarity** between users input and our accepted example sentence. So what we actually need just create a matrix for them and count **Cosine similarity** for them to get the command type.

**Comment by LittleYenMin** [comment]
> > here it's the step I plan to do with TF-IDF and cosine similarity
> > 
> > 1. analysis of the TF-IDF value of the text sequence by jieba.
> > 2. cosine similarity all listed questions.
> > 3. return and rank the top N result
> > 
> > what do you think?
> > References
> > [基于 TF-IDF 算法的关键词抽取(jieba)](https://github.com/fxsjy/jieba#%E5%9F%BA%E4%BA%8E-tf-idf-%E7%AE%97%E6%B3%95%E7%9A%84%E5%85%B3%E9%94%AE%E8%AF%8D%E6%8A%BD%E5%8F%96)
> > [TF-IDF与余弦相似性的应用](http://www.ruanyifeng.com/blog/2013/03/cosine_similarity.html)
> 
> Please more carefully pick the reference, Jieba is based on TF_IDF to get keywords, not give you the TF_IDF matrix.

it took keyword by TF-IDF algorithm; it's mean we can get the TF-IDF value by this method right?

**Comment by LittleYenMin** [comment]
alright, I know what TF-IDF means.

we need to set the weight for each word we care about like `想 = 10`, `成績=13`,` 曠課=17`, `課表=19`
something like this?

**Comment by dannypsnl** [comment]
For now, we better do not add weight on to words, that would make the algorithm too sensitive to certain words, for example, 成績 might also trigger our algorithm since we add too high weight for it

**Comment by LittleYenMin** [comment]
well... if we don't, how to calculate the weight for each word.

like `我想查成績` equal to 1, 1, 1, 1, 1
if we don't give a rule, the weight has no different.

**Comment by LittleYenMin** [comment]
关键词提取所使用逆向文件频率（IDF）文本语料库可以切换成自定义语料库的路径

用法： jieba.analyse.set_idf_path(file_name) # file_name为自定义语料库的路径
自定义语料库示例：https://github.com/fxsjy/jieba/blob/master/extra_dict/idf.txt.big
用法示例：https://github.com/fxsjy/jieba/blob/master/test/extract_tags_idfpath.py

**Comment by LittleYenMin** [comment]
after a lengthy discussion in the chat app, 
we decide to implement the cosine-similarity algorithm first.
#8
