### ISSUE TITLE
Use CSV as database to store question and answer.

### ISSUE THREAD

**Issue by LittleYenMin** [LittleYenMin/jieba-bot#9]
It seems like we already implement the cosine-similarity algorithm now,
Time to talk about the file format with the question and answer stored.

CSV looks like a simple and convient solution for now. (sperate with `, ` and `\n`)

any suggestion? @dannypsnl @YanHerChen 

Example
============
Header
------------
`question`, `answer`

body
------------
`我想查成績`, `昌昌;成績`

**Comment by dannypsnl** [comment]
Implement a trait for each format, for example:
interface JSON {
  from(str) -> any
  to() -> str
}

**Comment by LittleYenMin** [comment]
@dannypsnl  I don't get it, I think we got a misunderstanding.

actually, I mean use CSV as the database to store question and answers.

**Comment by dannypsnl** [comment]
> @dannypsnl I don't get it, I think we have a misunderstanding.
> 
> actually, I mean use CSV as the database to store question and answers.

Quite easy, I think the format of data should not need to have a discussion, take a convenient solution for you. What I would care is the content of data, how do you sure underlying format won't make the type became hard to transform to others format if not, I have no opinion here.

**Comment by LittleYenMin** [comment]
#10

**Comment by dannypsnl** [comment]
So we could close the issue?

**Comment by LittleYenMin** [comment]
> So we could close the issue?

sure.
